### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by burkesquires** [AnaCoda/Discord_NLP_Reminder_Bot_Public#1]
Hi Ana,
Congratulations on the project and the publicity (https://blogs.nvidia.com/blog/2021/01/06/ana-ducristea-jetson-app/?ncid=em-news-53015-vt16#cid=ix01_em-news_en-us). 

This looks like a very interesting project, especially in light of the privacy concerns with projects like Amazon's Echo and Google Assistant.

One thing that can help a project is to add a software license to the project. What this means is update the GitHub project to pick a license and then the license file will be added to the project. By specifying a license it helps people (or companies) know what they can and cannot do with the code you have release. You can learn more about license by looking here: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository . Additionally, I find this website helps many to choose which license they would like to pick: https://choosealicense.com.

I would be happy to answer any questions you may have. I plan to check it out.

Regards

**Comment by AnaCoda** [comment]
Thank you Burke, good idea! I have done so and I will also try to choose licenses for my other unlicensed projects.
